### ISSUE TITLE
MenuPrincipal.java

### ISSUE THREAD

**Issue by ImMavz** [Samth18/Miniproyecto#7]
En el archivo MenuPrincipal.java hay un error que impide ejecutar el código después de haber usado la primera opción, según el error tiene que ver con la línea 20 que es el opcion = scanner.nextByte(); 
El error consiste en básicamente después de usar la opción 1) Ingresar candidato y rellenar los datos hasta los votos, una vez finalizado devuelve el menú principal junto a las opciones, solo que termina de ejecutarse el programa sin ejecutarse el bucle do while. Cualquier idea o cambio en el código es mas que bienvenida.

**Comment by Intisma** [comment]
Hola! Diria que el error está en realidad en el código de InsertarCandidato, ya que se están creando múltiples instancias del scanner, para cada uno de los campos, aunque en realidad todos están leyendo el mismo input. He hecho un pull request usando el mismo scanner para todas las lecturas que en mi caso ha resuelto el error.

**Comment by Juanito215** [comment]
Listo mi papasho. El error estaba en no cerrar el scanner en el archivo crud (insertar candidato).
